language: node_js
node_js:
- '6'
before_install:
- npm install gulp
install:
- npm install --ignore-scripts
script:
- npm run lint && gulp build
before_deploy:
- gulp dist
deploy:
- provider: npm
  email: jesper@starkar.no
  api_key:
    secure: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_TAG =~ ^v[0-9]\.[0-9]\.[0-9]$
    repo: SuperFlyTV/casparcg-connection
notifications:
  email:
    recipients:
    - jesper@superfly.tv
    on_success: change
    on_failure: change
  slack:
    secure: $SLACK_TOKEN
