language: node_js
node_js:
- '6'
before_install:
- npm install -g gulp
install:
- npm install --ignore-scripts && typings install
script:
- gulp build
deploy:
  provider: npm
  email: jesper@superfly.tv
  api_key:
    secure: NEBXS9TANvOz4VVFJ1g0GJMbXbV0UIhGvWn2HUCTAFZhLezeMAooe70Cq5SGW9YfG7pIhrVQjV+WS4JST7Ej3dkNEsy5pPBsCao4wAvigUZ2jutzlC3Ayb+7dbi0O12hwJLKPpEKkJBzFHAirpKLtDwbV+OR+WtEP0JSXiMIQ576m5KrNmFkF7P2uLa4ZdTf1MUZyk6ieQmRoMMyaKv536ytSDUzqAIpzcgRTmBEUJ3kpj0q9LMQ+IETZ1IylMuvlOUKdgLg/eOaDnCDGQhnR9V7jaErmOm8Ognw4aUtVz6G+WwvIxKR3p2WqnA9oOw8MTf4qQHkbIYEmQuq1o4Y9iVyPvZ6mErHl0jQrBxGT7PcWxhcqyb/9tfjFCua9H+SYJbhX3sPX4yeFPYAw3QJZAPX4kuK114dM6Ar9Dp0mxzrrAFeVjwZRFsVvvWMT6ILHEZUiodGxq5sIw0b1EIGhd+gJ5Mo0dMmiNWZHQ1VjN5IEoghKYvv/GYfnZXHndIcKKhph4mlKzXlvp2ILr65LNQ7086BEhbEbwvg4DiQT4cdmP0GAFYeb5zZR2ACY5ayf/p9im5OMCf7Jy9kpSe+lvXo6oH/eNYaAzoqUNturNZ4/zyntUa03MfLIj0CkuLnJ9L3f4LfpNzOVFofX49qdh8EcckXjhmt//MU4RiP2CY=
  skip_cleanup: true
  on:
    tags: true
    repo: SuperFlyTV/casparcg-connection
    branch: master
