language: node_js
node_js:
- '6'
before_install:
- npm install -g gulp
install:
- npm install --ignore-scripts && typings install
script:
- gulp build
deploy:
  provider: releases
  api_key:
    secure: aTsxwE6e4UYicYqI8FwfMFfMHCuRYi2iLwsAzuS0trTKd1KeO6wSfvXNRTYX+whA7Tj+cdgaH9qgBd9DDIe6fl4xpT3ffmxLz2SmQ3v3ecvW4KtqOk8rNeFytqUufdnlSN2ky6aiPr/zITBMFNhiw3Uqgd5RUZQ6pFYWQUGHKBgeiqVDcWoQpgsxxer9UlbjgoznsT1bB34PkLpVGaP1eNF79WJaU89mc0yETP4LvGti87DFB28Zs/anWKvpZ03KWvi+iL27EqnqLZAzhPqie+s7Us03PTbk3rFed2xpO8tCH7HoxEiTl5L8sgH4w+F/ZA9TC97k6NzmZK8vkVOxA/3QQcaFBBSXZPd1BwxP0LUJlmNgswyqpKY5hcbweTCBuOziGlQSZ7o3u01ABxu3QaonzAqz43jI3QhoKHgmGGZ+9UIqPFXX8Tfh1nhXQlCHkE9T8yCe3JjbX8j84G+4n2SSoWHTeMRoFyEv1JM+czyDqdb9xO8tEpj6FmstvCqL6+CN5ZeqFX77802FK8yuE6iJUby3gaktOC38FDkqrfWTvadRcJ0cDX7Cvrvxg4cx2VUXqub/ETR2A70C9GACGj0eUfwKJ4GIb2IOEuqHzy1ZzsgzMrNDz0Y3OEVIWcNNWmceMhu9k3usa8LdGvEfb6NqADcFmi0iRTz2A/DOX1Y=
  file: js/**/**.*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
 provider: npm
  email: "jesper@superfly.tv"
  key:
    secure: SOAjG8VtABP1J9Z/4LSPIgYTJnKeUhf8W7rQhxyDVoN6y9Z4yC6LUalaCF6fqczfPzfLyrZgiIqle/f4mDJPMgXP4Uu0rCB7/m80ObUXe5S/0ovLc4AlCGVIMkFD6Sv2k+ATiFEs0WXEft26OR5IXaAilrgk0FG6rC809NYXJjKsG1Di9LzOEn5Q7oNNtfD4sUb7SzHP2WZmzqYUxYzSETd4DKY5EFRFJ/U/U56j503NyESgf93IttPZzkwCWskpgcVsawzk8zSXWZWj+huze2t2VWAh2GWtLjx16faz3vHnNG7VrEX582Qasp7t6Tw7LJapG8NubYNSYgArA3qWwu6lfHjvTKbCYJp2dRbv75m4Is5QMjsqA7tNNfooBqpLcodNE7nGq6c0eXCDboRVlO3tm4gyQfq827VCV0awuD80MAVGgCfN8FtsbO4xsodGTz/wTZ+Uu0erBLFrb0VJEsvAkHy+HHfOewwdhIH1dr03hO8MWnAxlefaDB8kV+3BWHDz9qcNQkDmpIoW0egaxsFxPuIpFgiO/EFVa0wVEJaqeZj8tjDvE/oovdJBAMexYOlTkOta2xgPNa9b3YJqEquZJv9heDhDu6qAW4crVm+Lkcc6UUFifRfwbimSeqfLCqBo4Cnk9Bq33ZG86a/EOIksCGRD2/Ya3CuW9izZV40=
  on:
    tags: true