language: node_js
node_js:
- '6'
before_install:
- npm install -g gulp
install:
- npm install --ignore-scripts && typings install
script:
- gulp build
deploy:
  provider: npm
  email: jesper@superfly.tv
  api_key:
    secure: crb5w+WyPxrpFuhegQFsa9eGKRKo0Y5JoL6xfmhEejYod8vyJdUHtdc+AbdAgo1YfHfJ6kLW2ko7e8XDB0nKYD95kk0W4uU0i3bzTS1R4ZCTaWid/anWRmeAoE5WWAEAP378LzfkLr4Vr2XpILGZUZL4KMOaRbYLJW3HWjuEy5Lu5/DBVHsCpICpT/4RuZQmzAMBpC6D442RzOGOCUEfPJEZLKztX9s17nlDvi91Qqv5oNIkStbwR2DmIuANJV03at+ISqT3VCzKc1KeDVFuJrwmszGaEprLNbKfsYHc9Sib4jNtV94ZWoFgR7TcPRifEBsjEvFtpRZpFFPSdkTZ+MkiuSKa6UB5IcMocjH4Azd5UUglSWCgXrAYlOd5Z6cuVBvJl5DHRMCo9tWxrtUbKjKGeVZmjO1rmjmTEpo2oME4EfRuafSo1i+pwrkmgGKrj/BtIDX8CoatUB/y3h1MPSDgJ9BtDBYaJ8B9xwdZEh1FAjKVSLZc2mh/pOOOiJiWV/N5NEVcP5AZhov/41APUFPsguJFRISDRTsQMESskLPVenAfgGx1DzJ95V9dXMLyQ18KnacJDspHU0tnyUKTuaDmwAbe6Kap2JSz5olUZr43NKg/hnvnuvrCKGuJpmjfUOMLdKN3oJ+7K/SVcUfftLHhTYZ+ipYq9jg8pLzxdkY=
  on:
    tags: true
    repo: SuperFlyTV/casparcg-connection
    branch: master
