language: node_js
node_js:
- '6'
before_install:
- npm install -g gulp
install:
- npm install --ignore-scripts && typings install
script:
- gulp build
deploy:
- provider: npm
  email: "jesper@superfly.tv"
  key:
    secure: SOAjG8VtABP1J9Z/4LSPIgYTJnKeUhf8W7rQhxyDVoN6y9Z4yC6LUalaCF6fqczfPzfLyrZgiIqle/f4mDJPMgXP4Uu0rCB7/m80ObUXe5S/0ovLc4AlCGVIMkFD6Sv2k+ATiFEs0WXEft26OR5IXaAilrgk0FG6rC809NYXJjKsG1Di9LzOEn5Q7oNNtfD4sUb7SzHP2WZmzqYUxYzSETd4DKY5EFRFJ/U/U56j503NyESgf93IttPZzkwCWskpgcVsawzk8zSXWZWj+huze2t2VWAh2GWtLjx16faz3vHnNG7VrEX582Qasp7t6Tw7LJapG8NubYNSYgArA3qWwu6lfHjvTKbCYJp2dRbv75m4Is5QMjsqA7tNNfooBqpLcodNE7nGq6c0eXCDboRVlO3tm4gyQfq827VCV0awuD80MAVGgCfN8FtsbO4xsodGTz/wTZ+Uu0erBLFrb0VJEsvAkHy+HHfOewwdhIH1dr03hO8MWnAxlefaDB8kV+3BWHDz9qcNQkDmpIoW0egaxsFxPuIpFgiO/EFVa0wVEJaqeZj8tjDvE/oovdJBAMexYOlTkOta2xgPNa9b3YJqEquZJv9heDhDu6qAW4crVm+Lkcc6UUFifRfwbimSeqfLCqBo4Cnk9Bq33ZG86a/EOIksCGRD2/Ya3CuW9izZV40=
  on:
    tags: true